### ISSUE TITLE
Error occur on certain .bvh file

### ISSUE THREAD

**Issue by HYLee1008** [wyysf-98/GenMM#5]
Hi, thanks to your amazing work!

I've tried to run your code on my custom .bvh file. While some .bvh files work fine, there are also .bvh files that cause errors.
Here is the error message.
`Traceback (most recent call last):
  File "run_random_generation.py", line 116, in <module>
    generate(cfg)
  File "run_random_generation.py", line 78, in generate
    motion_data = [BVHMotion(cfg.input, skeleton_name=cfg.skeleton_name, repr=cfg.repr,
  File "/home/hylee/workspace/GenMM/dataset/bvh_motion.py", line 53, in __init__
    self.raw_data = BVH_file(bvh_file, skeleton_confs[skeleton_name] if skeleton_name is not None else None, requires_contact, joint_reduction, auto_scale=True)
  File "/home/hylee/workspace/GenMM/dataset/bvh/bvh_parser.py", line 96, in __init__
    self.anim = bvh_io.load(file_path)
  File "/home/hylee/workspace/GenMM/dataset/bvh/bvh_io.py", line 179, in load
    data_block = data_block.reshape(N, 6)
ValueError: cannot reshape array of size 813 into shape (137,6)`

It seems that errors occur if the number of channels for all joints is not the same. How can I hendle this problem?

**Comment by wyysf-98** [comment]
Hi, the current python bvh parser is not very stable and can not handle some special format .bvh file, such as different channels of joints.
I think you can try to import your custom .bvh file into Blender, and then export it, then you may get the correct format.  If you have any issues, please share more information about your motion file.

**Comment by wyysf-98** [comment]
Got it. I think I'll try to fix this to support more motion files in the future.

As for mixamo data, you can convert it using [fbx2bvh](https://github.com/DeepMotionEditing/deep-motion-editing/blob/master/blender_rendering/utils/fbx2bvh.py), which works fine on most data during my experiments.

**Comment by thomaskarado** [comment]
"Got it. I think I'll try to fix this to support more motion files in the future."  when gonna be?  I cant add bvh  ValueError: exemplar must be a bvh file or a txt file
